version: '3'
# docker-composeの書式のバージョンを指定します。(原則、最新を指定する)

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: ./
      dockerfile: ./ruby/Dockerfile
    working_dir: /blog
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - type: bind
        source: "./blog"
        target: "/blog"
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  mysql_data: